FROM node:9.11.1-alpine

MAINTAINER "Greg Milligan <xybersolve@gmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python && \
  apk add --no-cache krb5-dev zeromq-dev && yarn global add node-gyp

CMD [ "node" ]
