version: 2.0
jobs:
  deploy:
    machine:
      enabled: true
    working_directory: ~/zeromq-node-base
    environment:
    - DOCKER_IMAGE: xybersolve/zeromq-node-base
    - VERSION_PREFIX: 1.0
    steps:
    - checkout
    - run:
        name: Build image
        command: docker build -t ${DOCKER_IMAGE} .
    - run:
        name: Tag and deploy image to docker hub
        command: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}-${SHORT_SHA}"
          # tag with git sha
          docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE}:${VERSION}
          # tag as latest
          docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE}:latest
          # push to Docker Hub
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
          docker push ${DOCKER_IMAGE}
workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        context: xs-docker
        filters:
          branches:
            only: release
